
begin transaction;

DROP TABLE IF EXISTS TRADE_STATUS CASCADE;
DROP TABLE IF EXISTS TRADE CASCADE;
DROP TABLE IF EXISTS FRIENDS_STATUS CASCADE;
DROP TABLE IF EXISTS FRIENDS CASCADE;
DROP TABLE IF EXISTS USER_STATUS CASCADE;
DROP TABLE IF EXISTS USER_LOCKER CASCADE;
DROP TABLE IF EXISTS LOCKER_STATUS CASCADE;
DROP TABLE IF EXISTS LOCKER CASCADE;
DROP TABLE IF EXISTS MODULE_STATUS CASCADE;
DROP TABLE IF EXISTS MODULE CASCADE;

commit;